name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ matrix.python-version }}
        uv venv .venv
        uv sync --dev
    - name: Test
      run: |
        uv run pytest -v tests

  MacOS:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ matrix.python-version }}
        uv venv .venv
        uv sync --dev
    - name: Test
      run: |
        uv run pytest -v tests

  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      shell: bash
      run: |
        uv python install ${{ matrix.python-version }}
        uv venv .venv
        uv sync --dev
    - name: Test
      shell: bash
      run: |
        uv run pytest -v tests
